name: Nightwatch Tests
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x, 14.x, 16.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - name: Install Xvfb 
      run: sudo apt-get install -y xvfb wget
    - name: Dowload browsers
      run: |
        chmod +x ./scripts/download_browsers.sh
        ./scripts/download_browsers.sh

    - name: Install Google Chrome
      run: |
        chmod +x ./scripts/install_chrome.sh
        ./scripts/install_chrome.sh
    - name: Start Xvfb
      run: |
        export DISPLAY=':99.0'
        Xvfb :99 -screen 0 1440x900x24 > /dev/null 2>&1 &
    - run: npm test -- --verbose
